import assert from "node:assert/strict";
import { test } from "node:test";
import { BROAD_CATEGORIES, EXPERIENCE_FAMILIES, DEFAULT_VARIETY_CONFIG as config, calculateQuizVariety as score,
  canonicalVarietyTemplate, resolveVarietyExperience, resolveVarietyConfig, copyVarietyOverride, resetVarietyOverride,
  type VarietyQuestion, type VarietyConfig } from "./quizVariety";
function varied(): VarietyQuestion[] { return Array.from({ length: 40 }, (_, i) => ({ slot: i + 1, block: i < 20 ? 1 : 2,
  templateId: ["standard", "pixelbild", "meme_beschriften", "kunstwerk", "face_morph", "musik_rueckwaerts", "wahr_falsch", "schaetzfrage", "reihenfolge", "uebersetzt_vorgelesen"][i % 10], categories: [BROAD_CATEGORIES[i % 10]], tags: [], experience: EXPERIENCE_FAMILIES[i % 7] })); }
const themed: VarietyConfig = { ...config, mode: "THEMENQUIZ", theme: { categoryIds: ["Sport"], tags: [] } };
test("broad balanced quiz has high score and separate block analyses", () => { const r = score(varied(), config); assert.ok(r.score! >= 80); assert.equal(r.blocks.length, 2); assert.equal(r.provisional, false); });
test("one category loses theme balance even with diverse templates", () => { const q = varied().map(q => ({ ...q, categories: ["Sport"] })); assert.ok(score(q, config).score! < 75); assert.equal(score(q, config).metrics!.components.themeBalance, 0); });
test("one template loses breadth and balance even with many themes", () => { const r = score(varied().map(q => ({ ...q, templateId: "standard" })), config); assert.equal(r.metrics!.components.templateBalance, 0); assert.ok(r.score! < 80); });
test("many categories with standard text questions are not artificially diverse", () => { assert.ok(score(varied().map(q => ({ ...q, templateId: "standard", experience: "TEXT" })), config).score! < 60); });
test("many templates with one topic and one experience stay low", () => { assert.ok(score(varied().map(q => ({ ...q, categories: ["Sport"], experience: "TEXT" })), config).score! < 60); });
test("monotony produces slot-specific improvement hint", () => { const r = score(varied().map(q => ({ ...q, experience: "TEXT" })), config); assert.ok(r.hints.some(h => h.code === "MONOTONY:1" && h.slot === 3)); });
test("global balance cannot mask poorly balanced blocks", () => { const q = varied().map(q => ({ ...q, categories: [q.block === 1 ? "Musik" : "Sport"] })); const r = score(q, config); assert.ok(r.score! < 75); assert.ok(r.calculation!.blockCeiling! < 80); });
test("ignored category suppresses missing hint but preserves actual dominance", () => { const ignored = { ...config, ignoredCategories: ["Religion & Weltanschauung"] }; assert.ok(!score(varied(), ignored).hints.some(h => h.code === "MISSING_CATEGORY:Religion & Weltanschauung")); const r = score(varied().map(q => ({ ...q, categories: ["Religion & Weltanschauung"] })), ignored); assert.equal(r.metrics!.categories["Religion & Weltanschauung"], 40); assert.ok(r.hints.some(h => h.code === "DOMINANT_CATEGORY:Religion & Weltanschauung")); });
test("disabled analysis returns neither score nor warnings", () => { const r = score(varied(), { ...config, mode: "DEAKTIVIERT" }); assert.equal(r.score, null); assert.deepEqual(r.hints, []); assert.equal(r.metrics, null); });
test("themed quiz rewards explicit membership and does not warn about missing categories", () => { const r = score(varied().map(q => ({ ...q, categories: ["Sport"] })), themed); assert.equal(r.metrics!.components.themeBreadth, 20); assert.ok(!r.hints.some(h => h.code.startsWith("MISSING_CATEGORY"))); });
test("themed quiz flags only verified foreign question", () => { const q = varied().map(q => ({ ...q, categories: ["Sport"] })); q[0].categories = ["Musik"]; const r = score(q, themed); assert.equal(r.metrics!.foreign, 1); assert.ok(r.hints.some(h => h.code === "FOREIGN_QUESTIONS")); });
test("uncategorized themed question is uncheckable, not foreign", () => { const q = varied().map(q => ({ ...q, categories: ["Sport"] })); q[0].categories = []; const r = score(q, themed); assert.equal(r.metrics!.foreign, 0); assert.equal(r.metrics!.uncheckable, 1); assert.equal(r.provisional, true); });
test("explicit themed tag can verify membership", () => { const r = score(varied().map(q => ({ ...q, tags: ["Harry Potter"] })), { ...themed, theme: { categoryIds: [], tags: ["Harry Potter"] } }); assert.equal(r.metrics!.foreign, 0); assert.equal(r.metrics!.uncheckable, 0); });
test("undefined themed scope produces configuration state without score", () => { const r = score(varied(), { ...themed, theme: { categoryIds: [], tags: [] } }); assert.equal(r.status, "INCOMPLETE_THEME"); assert.equal(r.score, null); });
test("event-series inheritance, atomic override and reset", () => { assert.equal(resolveVarietyConfig(themed, null).config.mode, "THEMENQUIZ"); const override = { ...config, mode: "DEAKTIVIERT" as const }; assert.deepEqual(resolveVarietyConfig(themed, override).config, override); assert.deepEqual(resolveVarietyConfig(themed, resetVarietyOverride()).config, themed); });
test("copy preserves explicit override or inherits target event series", () => { const copy = copyVarietyOverride(themed); assert.deepEqual(copy, themed); assert.notEqual(copy, themed); assert.equal(copyVarietyOverride(null), null); assert.deepEqual(resolveVarietyConfig(config, copyVarietyOverride(null)).config, config); });
test("empty and tiny quizzes are provisional, finite and not highly diverse", () => { assert.equal(score([], config).score, 0); const r = score(varied().slice(0, 4), config); assert.equal(r.provisional, true); assert.ok(Number.isFinite(r.score)); assert.ok(r.score! < 80); });
test("missing categories reduce theme components according to coverage", () => { const q = varied(); q.slice(0, 12).forEach(q => { q.categories = []; }); const r = score(q, config); assert.equal(r.metrics!.categoryCoverage, 0.7); assert.ok(r.metrics!.components.themeBreadth <= 14); assert.equal(r.provisional, true); });
test("unpublished questions are included, status does not affect variety", () => { assert.deepEqual(score(varied(), config), score(varied().map(q => ({ ...q, reviewStatus: "DRAFT" })), config)); });
test("legacy aliases and dynamic bases count as canonical templates", () => { assert.equal(canonicalVarietyTemplate("image_pixel"), "pixelbild"); assert.equal(canonicalVarietyTemplate("multiple-choice"), "standard"); const r = score(varied().map(q => ({ ...q, templateId: "custom", baseTemplateId: "image_pixel" })), config); assert.deepEqual(r.metrics!.templates, { pixelbild: 40 }); });
test("solution image does not turn text question into visual experience", () => { assert.equal(resolveVarietyExperience({ templateId: "fakten_jahr", questionHasVisual: false, questionHasAudio: false }), "TEXT"); assert.equal(resolveVarietyExperience({ templateId: "standard", questionHasVisual: true, questionHasAudio: false }), "VISUAL"); });
test("hint priority, top-three limit and input-order independence are deterministic", () => { const q = varied().map(q => ({ ...q, categories: [] })); const r = score(q, config); assert.equal(r.topHints.length, 3); assert.equal(r.hints[0].priority, 1); assert.deepEqual(r, score([...q].reverse(), config)); });
test("pause is excluded from transitions and monotony", () => { const q = varied().map(q => ({ ...q, experience: "TEXT" as const })); const r = score(q, config); assert.equal(r.metrics!.transitions, 38); assert.equal(r.metrics!.longestRun, 20); });
test("dual categories share one unit and excessive tagging cannot inflate score", () => { const q = varied().map(q => ({ ...q, categories: ["Musik", "Sport"] })); assert.deepEqual(score(q, config).metrics!.categories, { Musik: 20, Sport: 20 }); q[0].categories = ["Musik", "Sport", "Geschichte"]; assert.equal(score(q, config).metrics!.invalidCategories, 1); });
test("unknown experience and non-consecutive slots do not invent switches", () => { const q = varied().slice(0, 5); q[2].experience = null; q[4].slot = 9; const r = score(q, config); assert.equal(r.metrics!.transitions, 1); assert.equal(r.provisional, true); });
test("duplicate slots fail rather than inflating counts", () => { const q = varied(); q[1].slot = 1; assert.throws(() => score(q, config), /DUPLICATE_SLOT/); });

test("unknown dynamic bases cannot inflate template diversity", () => { const r = score(varied().map((q,i) => ({ ...q, templateId: `unknown-${i}` })), config); assert.equal(r.metrics!.components.templateBreadth,0); assert.equal(r.metrics!.templateCoverage,0); assert.equal(r.provisional,true); });
test("uncategorized question with unrelated tags is not automatically foreign", () => { const r=score(varied().map(q=>({...q,categories:[],tags:["Logo"]})),{...themed,theme:{categoryIds:[],tags:["Harry Potter"]}});assert.equal(r.metrics!.foreign,0);assert.equal(r.metrics!.uncheckable,40); });
