import { readFileSync, writeFileSync } from 'node:fs';
const dir = new URL('./', import.meta.url);
const read = name => JSON.parse(readFileSync(new URL(name, dir), 'utf8'));
const save = (name, content) => writeFileSync(new URL(name, dir), content, 'utf8');
const esc = value => String(value ?? 'nicht verifiziert').replaceAll('|', '\\|').replaceAll('\n', ' ');
const table = (columns, rows) => `| ${columns.join(' | ')} |\n| ${columns.map(() => '---').join(' | ')} |\n${rows.map(row => `| ${row.map(esc).join(' | ')} |`).join('\n')}\n`;
const intro = '# Redaktionelle Entwürfe – Paule II / Oktober\n\nStand: 7. Oktober 2026. Keine Freigabe, kein Import, keine finale Quizzuordnung. Schwierigkeiten und Oberkategorien sind redaktionelle Vorschläge.\n\n';
const a = read('anagrams.json'), e = read('estimates.json'), s = read('slots.json'), p = read('candidate-pairs.json'), gaps = read('content-gaps.json');
save('anagrams.md', intro + '50 unterschiedliche Personen; 50/50 exakte Buchstabenidentität nach der bestehenden Editor-Normalisierung. Umlaute werden zerlegt, Leerzeichen und Satzzeichen entfernt; ß bleibt ß. Die Namen verwenden die dokumentierte Schreibweise, beispielsweise Cleopatra. Alle Datensätze bleiben EDITORIAL_DRAFT. Bekanntheit, Wortwitz und Spielbarkeit benötigen eine redaktionelle Durchsicht.\n\n' + table(['ID', 'Anagramm', 'Lösung', 'Kategorie', 'Schwierigkeit', 'Personenreferenz'], a.map(r => [r.id, r.anagram, r.solution, r.category, r.difficulty, `[Referenz](${r.identitySource})`])));
save('estimates.md', intro + '50 Fragen mit recherchierten Quellen, Einheiten und Referenzwerten. Jede Quelle ist beim Datensatz verlinkt. Quellenprüfung ist keine automatische redaktionelle Freigabe. Rundungen, historische Regeln und zeitabhängige Werte sind ausdrücklich bezeichnet. Eine Bewertungstoleranz ist noch nicht festgelegt.\n\n' + table(['ID', 'Frage', 'Referenzwert / Einheit', 'Kategorie', 'Schwierigkeit', 'Zeitbezug', 'Quelle', 'QA / Erläuterung'], e.map(r => [r.id, r.question, `${r.referenceValue} ${r.unit}`, r.category, r.difficulty, r.referenceDate ?? 'stabil / sachbezogen', `[${r.sourcePublisher}](${r.source})`, r.explanation])));
save('slot-plan.md', intro + 'Gemeinsame Reihenfolge für beide Quizze: 20 Fragen pro Block. Pixel und Meme jeweils in beiden Blöcken. Übersetzt vorgelesen: ausschließlich Product Owner. Fragezeiten je Block 41 Minuten; mit je vier Minuten Moderationspuffer, fünf Minuten Einstieg, 15 Minuten Pause und zehn Minuten Abschluss sind 120 Minuten geplant. Generalprobe muss diese Zeitannahme prüfen.\n\n' + table(['Slot', 'Block', 'Template', 'Erlebnisfamilie', 'Schwierigkeit', 'Sekunden', 'Dramaturgie'], s.map(r => [r.slot, r.block, r.templateId, r.experience, r.difficulty, r.seconds, r.purpose])));
save('candidate-pairs.md', intro + 'Die IDs stammen aus früheren UI-Beobachtungen. Aktueller Review-Status, Medien, Wiederholungen und Verfügbarkeit sind durchgehend nicht vollständig verifiziert. NEU bezeichnet eine Idee, noch keine gespeicherte Frage. Kategorien werden ausschließlich in dieser Planung vorgeschlagen und ändern keine Bestandsfrage. Unbekannte Pixelmotive und FaceMorph-Lösungen verhindern noch eine vollständige Dublettenprüfung.\n\n' + table(['Slot', 'Template', 'Paule-II-Kandidat', 'Oktober-Kandidat', 'Schwierigkeit', 'Kategorie Paule / Oktober', 'Status', 'QA nötig'], p.map(r => [r.slot, r.templateId, r.pauleCandidate, r.oktoberCandidate, r.difficulty, `${r.pauleCategories.join(', ')} / ${r.oktoberCategories.join(', ')}`, `${r.status}; Production ungeprüft`, r.qaNeeded])));
save('content-gaps.md', intro + 'Bedarf gilt für beide Quizze zusammen. Bekannt ist ein partieller früherer UI-Bestand, kein vollständiger Export. „Vorläufig geeignet“ bedeutet Planungskandidat, nicht freigegeben oder mediengeprüft. Tatsächlich verifizierte Production-Lücken sind unbekannt. Lokale Pools schließen den redaktionellen Entwurfsbedarf bei Anagrammen und Schätzfragen, nicht den Import-/QA-Bedarf.\n\n' + table(['Template', 'Benötigt', 'Bekannt Production', 'Vorläufig geeignet', 'Planungslücke', 'Anmerkung'], gaps.map(r => [r.templateId, r.needed, r.presentKnownProduction, r.usableProvisional, r.missingPlanning, r.note])));
const distribution = (rows, key) => {
  const counts = new Map();
  for (const row of rows) for (const category of row[key]) counts.set(category, (counts.get(category) ?? 0) + 1 / row[key].length);
  return [...counts].sort((a,b) => b[1] - a[1] || a[0].localeCompare(b[0], 'de'));
};
save('planning-comparison.md', intro + 'Planungsvergleich, kein Vergleich gespeicherter Quizinhalte. Beide Quizze besitzen dieselben 40 Templates und vorgesehenen Schwierigkeiten, dieselben Erlebnisfamilien und dieselbe Blockstruktur. Die zwei Blöcke wechseln bei Slot 20/21 über die Pause.\n\n' + table(['Merkmal', 'Paule II (#30)', 'Oktober (#31)'], [['Fragen / Blöcke', '40 / 20+20', '40 / 20+20'], ['Eventreihe (frühere UI-Beobachtung)', 'Phliipps Testwiese; gewünschte Korrektur vorgemerkt', 'LOVD'], ['Rolle', 'Generalprobe', 'Premiere'], ['Templatearten', '15', '15'], ['Erlebnisfamilien', '7', '7'], ['Identische bekannte Frage-IDs', '0; unbekannte Motive noch prüfen', '0; unbekannte Motive noch prüfen'], ['Identische Lösungen / Medien', 'noch nicht vollständig überprüfbar', 'noch nicht vollständig überprüfbar'], ['Variety-Score / Block-Scores', 'nicht berechnet ohne verifizierte Metadaten', 'nicht berechnet ohne verifizierte Metadaten']]) + '\n## Vorgeschlagene Themenanteile\n\nMehrfachkategorien teilen einen Slot gleichmäßig. Vorschläge sind keine gespeicherte Klassifikation.\n\n' + table(['Quiz / Block', 'Kategorie', 'Slotanteil'], ['pauleCategories','oktoberCategories'].flatMap(key => [0,1,2].flatMap(block => distribution(block ? p.filter(r => r.block === block) : p, key).map(([category,count]) => [`${key === 'pauleCategories' ? 'Paule II' : 'Oktober'} / ${block || 'gesamt'}`, category, count.toFixed(1)])))));
