import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { isExactAnagram, normalizeAnagramLetters, parseQuestionTemplateData } from "../../app/fragen/editor/templates/questionTemplateData";

const dir = new URL("./", import.meta.url);
const BROAD_CATEGORIES = JSON.parse(readFileSync(new URL("proposed-categories.json", dir), "utf8")) as string[];
const anagrams = JSON.parse(readFileSync(new URL("anagrams.json", dir), "utf8")) as Array<{ id: string; person: string; anagram: string; solution: string; category: string; difficulty: string; identitySource: string; status: string; templateId: string; templateConfig: { templateData: unknown } }>;
const estimates = JSON.parse(readFileSync(new URL("estimates.json", dir), "utf8")) as Array<{ id: string; question: string; referenceValue: number; unit: string; referenceDate: string | null; source: string; retrievedAt: string; category: string; difficulty: string; status: string; releaseApproved: boolean; templateId: string; templateConfig: { templateData: unknown } }>;
const slots = JSON.parse(readFileSync(new URL("slots.json", dir), "utf8")) as Array<{ slot: number; block: number; templateId: string; experience: string; difficulty: string; seconds: number; finalAssignment: boolean }>;
const pairs = JSON.parse(readFileSync(new URL("candidate-pairs.json", dir), "utf8")) as Array<{ slot: number; templateId: string; pauleCandidate: string; oktoberCandidate: string; qaNeeded: string; status: string; currentStatusVerified: boolean }>;
function checkMix(rows: Array<{ difficulty: string }>) { assert.deepEqual(["LEICHT", "MITTEL", "SCHWER"].map(d => rows.filter(r => r.difficulty === d).length), [15,25,10]); }
test("50 distinct people and 50 exact nonempty anagrams, 15/25/10 difficulty", () => { assert.equal(anagrams.length,50); assert.equal(new Set(anagrams.map(r => normalizeAnagramLetters(r.person))).size,50); assert.equal(new Set(anagrams.map(r => r.anagram)).size,50); for(const r of anagrams){ assert.ok(r.person.trim() && r.anagram.trim() && r.solution.trim()); assert.ok(isExactAnagram(r.person,r.anagram),r.id); assert.ok(r.anagram.split(/\s+/).length>=2 && r.anagram.split(/\s+/).length<=4); assert.ok(new URL(r.identitySource).protocol === "https:"); } checkMix(anagrams); });
test("diacritic normalization is stable and shared with existing editor", () => { assert.equal(normalizeAnagramLetters("Ä.-Ö Ü-é"),normalizeAnagramLetters("aoue")); assert.notEqual(normalizeAnagramLetters("ß"),normalizeAnagramLetters("ss")); assert.ok(isExactAnagram("Thomas Müller","Smaller Mouth")); assert.ok(!isExactAnagram("Marie Curie","Marie Cure")); });
test("all 100 draft candidates pass complete structured template parsing", () => { for(const r of [...anagrams,...estimates]){ assert.ok(parseQuestionTemplateData(r.templateConfig.templateData,r.templateId,true),r.id); assert.equal(r.status,"EDITORIAL_DRAFT"); } });
test("50 estimates have sources, units, finite values, categories and balanced difficulty", () => { assert.equal(estimates.length,50); assert.equal(new Set(estimates.map(r=>r.question.toLowerCase())).size,50); assert.equal(estimates.filter(r=>r.source).length,50); for(const r of estimates){assert.ok(Number.isFinite(r.referenceValue));assert.ok(r.unit.trim());assert.ok(new URL(r.source).protocol === "https:");assert.equal(r.retrievedAt,"2026-10-07");assert.ok((BROAD_CATEGORIES as readonly string[]).includes(r.category));assert.equal(r.releaseApproved,false);} checkMix(estimates);const counts=new Map<string,number>();for(const r of estimates)counts.set(r.category,(counts.get(r.category)??0)+1);assert.ok(Math.max(...counts.values())<=10); });
test("time-dependent estimate references are explicitly dated", () => { const required=["EST-09","EST-13","EST-14","EST-15","EST-21","EST-23","EST-25","EST-30","EST-32","EST-33","EST-34","EST-35","EST-36","EST-38","EST-39","EST-40","EST-41","EST-42","EST-43","EST-45","EST-46","EST-47","EST-48"];for(const id of required)assert.ok(estimates.find(r=>r.id===id)?.referenceDate,id); });
test("40 slots, 20 per block, same paired sequence with no final assignments", () => {assert.equal(slots.length,40);assert.deepEqual(slots.map(s=>s.slot),Array.from({length:40},(_,i)=>i+1));assert.deepEqual([1,2].map(b=>slots.filter(s=>s.block===b).length),[20,20]);assert.equal(new Set(slots.map(s=>s.templateId)).size,15);for(const s of slots)assert.equal(s.finalAssignment,false);for(const p of pairs){assert.equal(p.templateId,slots[p.slot-1].templateId);assert.notEqual(p.pauleCandidate,p.oktoberCandidate);assert.ok(p.qaNeeded && p.status);assert.equal(p.currentStatusVerified,false);} });
test("Pixel and Meme learning curve and PO translation slots in both blocks", () => {for(const b of [1,2])for(const t of ["pixelbild","meme_beschriften","uebersetzt_vorgelesen"])assert.equal(slots.filter(s=>s.block===b&&s.templateId===t).length,1);assert.equal(slots.find(s=>s.block===1&&s.templateId==="pixelbild")?.difficulty,"LEICHT");assert.equal(slots.find(s=>s.block===2&&s.templateId==="pixelbild")?.difficulty,"SCHWER");assert.ok(pairs.filter(p=>p.templateId==="uebersetzt_vorgelesen").every(p=>p.status==="PRODUCT_OWNER")); });
test("sequence avoids four repeated experience families and stays within two-hour budget", () => { for(const b of [1,2]){const block=slots.filter(s=>s.block===b);let run=1;for(let i=1;i<block.length;i++){run=block[i].experience===block[i-1].experience?run+1:1;assert.ok(run<4);}assert.ok(block.reduce((sum,s)=>sum+s.seconds,0)<=45*60);} });
